---
name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  linux:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Update apt index
      run: sudo apt-get update -qq
    - name: Install SFML
      run: sudo apt-get install libsfml-dev
    - name: Checkout EmptyEpsilon
      uses: actions/checkout@v2
    - name: Build and test
      run: docker/build.sh
  windows-cross:
    name: Windows Cross-Compile
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt update -qq
          sudo apt install build-essential cmake python3-minimal mingw-w64 ninja-build p7zip-full
      - name: SeriousProton
        uses: actions/checkout@v2
        with:
          repository: daid/SeriousProton
          path: SeriousProton  
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: EmptyEpsilon
      - name: Build
        run: |
          mkdir -p _build_win32
          cd _build_win32
          cmake ../EmptyEpsilon -G Ninja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_TOOLCHAIN_FILE=/cmake/mingw.toolchain -DSERIOUS_PROTON_DIR=../SeriousProton
          ninja package
        
