---
name: macOS Package
on:
  push:
    branches:
      - macos-package
  pull_request:
jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.9
    steps:
      - name: Dependencies
        run: |
          brew install cmake ninja
          wget https://www.sfml-dev.org/files/SFML-2.5.1-macOS-clang.tar.gz
          tar xzf SFML-2.5.1-macOS-clang.tar.gz
      - name: SeriousProton Checkout
        uses: actions/checkout@v2
        with:
          repository: gcask/SeriousProton
          path: SeriousProton  
      - name: EmptyEpsilon Checkout
        uses: actions/checkout@v2
        with:
          path: EmptyEpsilon
      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: >
          cmake ../EmptyEpsilon
          -G Ninja
          -DCMAKE_BUILD_TYPE=RelWithDebInfo
          -DSFML_ROOT=../SFML-2.5.1-macOS-clang/Frameworks
          -DSERIOUS_PROTON_DIR=../SeriousProton
          -DCPACK_GENERATOR=DragNDrop
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --parallel --target EmptyEpsilon --verbose
      - name: Copy SFML
        run: |
          cp -r SFML-2.5.1-macOS-clang/Frameworks SFML-2.5.1-macOS-clang/extlibs build/
          ls build
      - name: Package
        working-directory: ${{github.workspace}}/build
        run: cpack --config CPackConfig.cmake --verbose
      - name: Upload Package
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/EmptyEpsilon.dmg
          draft: true
          prerelease: true