---
name: Alpine Pi2B
on:
  push:
    branches:
      - sdl-edge
  pull_request:
  workflow_dispatch:
jobs:
  rpi2b:
    name: Alpine RPi2
    runs-on: ubuntu-latest
    container: alpine:3.13
    steps:
    #### Setup #######
    - name: Sysroot setup
      run: |
        mkdir /sysroot
        apk --root /sysroot --initdb --arch armv7 add
        cp /etc/apk/repositories /sysroot/etc/apk
        apk --root /sysroot --allow-untrusted add alpine-keys
        apk --root /sysroot update
    - name: Sysroot build base
      run: apk --root /sysroot add build-base
    - name: Sysroot eudev
      if: ${{ false }}
      run: apk --root /sysroot add eudev-dev
    - name: Sysroot packages
      run: >
        apk --root /sysroot add mesa-dev sdl2-dev
        freetype-dev flac-dev libogg-dev libvorbis-dev openal-soft-dev
    - name: Host setup
      run: |
        apk add clang lld git cmake ninja llvm wget unzip
    - name: EmptyEpsilon Checkout
      uses: actions/checkout@v2
      with:
        path: EmptyEpsilon
        submodules: true

    ####### SFML ##############
    - name: SFML - Get Sources
      run: |
        wget https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip
        unzip SFML-2.5.1-sources.zip
    - name: SFML - Configure
      run: >
        cmake -G Ninja
        -DCMAKE_BUILD_TYPE:STRING=Release
        -DCMAKE_INSTALL_PREFIX:PATH=/sysroot/opt/sfml
        -DBUILD_SHARED_LIBS:BOOL=ON
        -DSFML_BUILD_EXAMPLES:BOOL=OFF
        -DSFML_BUILD_DOC:BOOL=OFF
        -DSFML_BUILD_GRAPHICS:BOOL=OFF
        -DSFML_BUILD_WINDOW:BOOL=OFF
        -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../EmptyEpsilon/cmake/rpi2b-alpine.toolchain
        -S SFML-2.5.1 -B sfml-build
    - name: SFML - Install
      run: cmake --build sfml-build --parallel --target install
    - name: SFML - Fix up
      run: |
        cd /sysroot/opt/sfml/include
        rm -rf Window Graphics GpuPreference.hpp Graphics.hpp OpenGL.hpp Window.hpp
    
    ###### EmptyEpsilon ##########
    - name: Configure CMake
      run: >
        cmake
        -G Ninja
        -DSFML_ROOT:PATH=/opt/sfml
        -DCMAKE_INSTALL_PREFIX:STRING=dist
        -DCPACK_GENERATOR:STRING=ZIP
        -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
        -DCMAKE_TOOLCHAIN_FILE:FILEPATH=EmptyEpsilon/cmake/rpi2b-alpine.toolchain
        -S EmptyEpsilon -B ee-build
    - name: Build
      run: cmake --build ee-build --parallel --target package
    - uses: actions/upload-artifact@v2
      with:
        name: emptyepsilon-alpine.zip
        path: ${{ github.workspace }}/build/EmptyEpsilon.zip
